name: chibby
description: A Monster Hunter World Weakness Companion

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  font_awesome_flutter: "^8.5.0"
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.1
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

dev_dependencies:
  bloc_test: ^3.0.0
  flutter_launcher_icons: "^0.7.3"
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/monster/mh4u/
    - assets/monster/mhgu/
    - assets/monster/mhw/
    - assets/weakness/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
